alex_quotes = {
  "Monday0700": "Did you meditate? Did you gym? No you didn't. So go. Now. You useless POS.",
  "Tuesday0700": "Did you meditate? Did you gym? No you didn't. So go. Now. You useless POS.",
  "Wednesday0700": "Did you meditate? Did you gym? No you didn't. So go. Now. You useless POS.",
  "Thursday0700": "Did you meditate? Did you gym? No you didn't. So go. Now. You useless POS.",
  "Friday0700": "Did you meditate? Did you gym? No you didn't. So go. Now. You useless POS.",
  "Saturday0700": "Did you meditate? Did you gym? No you didn't. So go. Now. You useless POS.",
  "Sunday0700": "Did you meditate? Did you gym? No you didn't. So go. Now. You useless POS.",
  "Monday2200": "Please leave you computer and go read.",
  "Tuesday2200": "Please leave you computer and go read.",
  "Wednesday2200": "Please leave you computer and go read.",
  "Thursday2200": "Please leave you computer and go read.",
  "Friday2200": "Please leave you computer and go read.",
  "Saturday2200": "Please leave you computer and go read.",
  "Sunday2200": "Please leave you computer and go read.",
  "Monday2300": "If you're reading this, you should be in bed instead.",
  "Tuesday2300": "If you're reading this, you should be in bed instead.",
  "Wednesday2300": "If you're reading this, you should be in bed instead.",
  "Thursday2300": "If you're reading this, you should be in bed instead.",
  "Friday2300": "If you're reading this, you should be in bed instead.",
  "Saturday2300": "If you're reading this, you should be in bed instead.",
  "Sunday2300": "If you're reading this, you should be in bed instead.",
  "Monday1930": "Go practice Android",
  "Tuesday1930": "Go practice iOS",
  "Wednesday1930": "Go study Economics",
  "Thursday1930": "Go study Options Futures and Swaps because you didn't pay attention last year",
  "Friday1930": "Do some sketching",
  "Saturday1000": "Do some writing",
  "Sunday1000": "Read up on Big Data things",
}
